name: 2 - Reusable Workflows

on:
    workflow_dispatch:


jobs:
    deploy:
        uses: ./.github/workflows/reusable-workflows.yml
        with:
            target-directory: "./custom-actions/react-app"

    print-outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps: 
            - name: Print outputs
              run: |
                echo "Build status: ${{ needs.deploy.outputs.build-status }}"
                echo "URL: ${{ needs.deploy.outputs.url }}"