name: 3 - Reusable Workflows

on:
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/1-reusable-workflows.yml
        with:
            target-directory: .

    e2e-tests:
        uses: Isrealade/github-actions-course-example-e2e.git/.github/workflows/e2e.yml@6577841cef17e3eaa2590c5c968e62d36e92688d
        secrets:
            access-token: ${{ secrets.GH_TOKEN }}
