name: Working with Artifacts

on:
    workflow_dispatch:

env:
    build-artifact-key: app-${{ github.sha }}
    test-coverage-key: test-coverage-${{ github.sha }}

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./artifacts/react-app
        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            
            - name: Download cached dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: ./artifacts/react-app/node-modules
                key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Unit tests
              run: npm run test -- --coverage

            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.test-coverage-key }}
                path: artifacts/react-app/build

            - name: Build code
              run: npm run build

            - name: Upload build files
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.build-artifact-key }}
                path: artifacts/react-app/coverage

    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Download build files
              uses: actions/download-artifact@v4
              with:
                name: ${{ env.build-artifact-key }}
                path: build
            
            - name: Show folder structure
              run: ls -R
